### ISSUE TITLE
Vymazání nákladu neaktualizuje stav platby

### ISSUE THREAD

**Issue by che0** [che0/teh-tracker#3]
- Mám tiket s náklady a platbami, ve stavu proplaceno
- Odeberu platbu (přiřazením k jinému tiketu)
- Odeberu s ní související náklad
- Tiket je ve stavu "částečně proplaceno", ač by správně měl být v "proplaceno"

**Comment by che0** [comment]
Asi i https://tracker.wikimedia.cz/ticket/1022/

**Comment by che0** [comment]
1022 to byl, v říjnu 2016 mu byl odmazaný náklad, a nepropsalo se to do vlastností příslušného slepence

**Comment by urbanecm** [comment]
Transferred into https://phabricator.wikimedia.org/T195619.
