### ISSUE TITLE
Improve notifications

### ISSUE THREAD

**Issue by jmacura** [che0/teh-tracker#7]
Napíšu to česky: Některá hlášení mi přijdou nešťastně napsaná, protože nejde o notifikaci stavu, ale klikatelné odkazy vybízející k akci. Nejsem schopen z ruky vytáhnout pull-request (Django vidím poprvé v životě), protože netuším, kde všude ta změna má závislosti, ale odkážu přímo na konkrétní řádky v souboru s překlady. Týká se to jak českých, tak anglických výrazů.

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L145
-> presubmit

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L146
-> podat k předschválení

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L149
->preaccept

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L150
-> předschválit

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L153
->submit

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L154
->podat ke schválení

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L157
-> accept

https://github.com/che0/teh-tracker/blob/868f87dca37851bbce4e5ffefe4aa056a2018bee/trackersite/locale/cs_CZ/LC_MESSAGES/django.po#L158
-> schválit

Díky!

**Comment by jmacura** [comment]
Tak P.S. Teď vidím, že se ty samé zprávy zobrazují jinde i potom, co se daná akce stane (kde už dávají smysl v té stávající formulaci, že se _něco stalo_).
Takže správným řešením by bylo rozdělit každou z těch hlášek na dvě rozdílné zprávy, kdy první bude vybízet k akci, jak navrhuji, a druhá bude oznamovat provedení akce. Ale pochopím, když se vám s takovou prkotinou nebude ani jednomu chtít patlat...

**Comment by urbanecm** [comment]
Dovolím si poznamenat, že tohle je starší repozitar a neodpovídá současné codebase. Přesunul jsem Tracker do Wikimedia Gerritu, repo se jmenuje wikimedia-cz/tracker. Mirror na Githubu je wikimedia/wikimedia-cz-tracker. Stejně tak jsem přesunul issue tracker do Phabricatoru, projekt wmcz-tracker. 

Mě přijde "přidán stav podáno ke schválení" jako použitelná formulace, ale nejsi první, kdo s tímhle přišel. Mě se plýtvat časem nahrazením formulace vsude možné v source code rozhodně chtít nebude. Jestli chceš takový commit udělat ty, why not, velmi rád tě naučím, co a jak :) .

**Comment by jmacura** [comment]
To je docela zásadní informace, kterou by nebylo od věci napsat do README.
Na Gerritu ani na Phabu se moc necítím, ale díky za nabídku.

**Comment by urbanecm** [comment]
Možná by che0 mohl repozitar archivovat, možná tam jde nekde takovahle informace napsat. Gerrit a Phabricator je vcelku jednoduchý na používání :).

**Comment by che0** [comment]
V popisu máme

> Tracker for Wikimedia CZ grant projects, moved to https://gerrit.wikimedia.org/g/wikime…

ale archivace zní jako dobrý nápad. Provedu.
